### PR TITLE
Move material on Carpentry lessons to later module about the Carpentries

### PR DESCRIPTION
**Pull request by jcoliver**
Here's an implementation of such a move. It takes the Carpentries lesson information from episode 14 and moves it to episode 20 to follow the **Carpentry Community** section. However, this makes episode 20 pretty long (my updated estimate is 70 minutes teaching), so I'm not convinced that my solution is ideal.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
@jcoliver, I wonder if this would go better in the `20-practices` section?  I think that episode is currently titled "Carpentry practices + curricula" so that would work nicely.

**Comment by jcoliver** [comment]
@ChristinaLK Yar, good point. I was working off an old version.

**Comment by ChristinaLK** [comment]
@jcoliver let me know if you plan to update this PR or if we should close it.

**Comment by jcoliver** [comment]
@ChristinaLK Yar, go ahead and close it. If I can get to it, I'll start from a fresh branch (but if someone else it itching to get started, don't wait for me).

**Pull request closed without merging**
