### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by lexnederbragt**
Addresses first bug in #83

### CODE REVIEW

**Comment by ChristinaLK** [comment]
I'll wait on this until we decide whether we want to re-number the episodes.

**Comment by ErinBecker** [comment]
@ChristinaLK - we do want to renumber the episodes now that we've gotten rid of the coffee breaks and lunch break episodes.

**Comment by ChristinaLK** [comment]
Sure, so no one should fix links until the very end then -- we should make that clear / mark those issues as off limits.

**Comment by ErinBecker** [comment]
@lexnederbragt - I have a PR pending to change the numbering of all of the episodes (due to removal of coffee break and lunch episodes). Once that is through, I'm going to go through all of the episodes and make sure the within-lesson links are updated and update them in a single PR. Thanks for your attention to detail (as always :-) )

**Pull request closed without merging**
