### PR TITLE
Change 'STEM' to 'science'

### PR DESCRIPTION
**Pull request by lexnederbragt**
Hoping this is more inclusive.

### CODE REVIEW

**Comment by ErinBecker** [comment]
STEM is used in the US to mean "science, technology, engineering and mathematics". Use of this acronym may be too US-centric, but changing to "science" alone excludes folks doing outreach in engineering, math, etc. What about removing "STEM/science" and having the sentence read "I have taught informally through programs such as outreach . . . "?

**Comment by lexnederbragt** [comment]
I see your point.

This makes me think back about this PR https://github.com/swcarpentry/workshop-template/pull/371 resulting from this discussion https://github.com/swcarpentry/workshop-template/issues/367. But that doesn't help too much either, becasue 'research outreach' is not a thing. I am going for your suggestion to use STEM/science.

**Comment by raynamharris** [comment]
Does this questions need to specifically ask for outreach in science or related technical fields?

Or, could we say something like "community outreach". This way it doesn't matter is was technical or not, but it was something you did to spread knowledge in an informal setting.

**Comment by lexnederbragt** [comment]
I just saw 'Science outreach' has it's own [Wikipedia page](https://en.wikipedia.org/wiki/Science_outreach). Reading the definition there, I'm starting to think that that may be the better solution after all?

**Comment by maneesha** [comment]
I support removing explicit references to 'science' as well.  We're increasingly working with people in fields like economics, digital humanities, etc. and it would be good to use more inclusive language.

**Comment by ErinBecker** [comment]
Current language is "I have taught informally through outreach programs, hackathons, laboratory demonstrations, and similar activities." 

Closing this issue.

**Pull request closed without merging**
