### PR TITLE
Replace learning objectives with lesson study part 2

### PR DESCRIPTION
**Pull request by ErinBecker**
This PR replaces the episode on designing learning objectives with an episode on developing good exercises and getting feedback on exercises that workshop participants have written in previous episodes. This is based on feedback from multiple workshops that found the episode on learning objectives to be unhelpful and requested more focused feedback and guidance for writing good challenge problems (including the DIBSI training with @karenword @lexnederbragt and @smcclatchy). 

Comments and changes welcome!

### CODE REVIEW

**Comment by ChristinaLK** [comment]
When I prepare to teach I frequently think about "what do I want people to take away?" or "what are the 3-4 core ideas I want to convey?"  This isn't learning objectives per se, but I think of it that way.  I feel like it's worth having something in the instructor training that discusses thinking about objectives at the lesson level.  Maybe for the next release.

**Comment by ErinBecker** [comment]
Thanks @ChristinaLK. Because this is a relatively major change, I'm going to wait for approval from at least one other Trainer before merging.

**Comment by karenword** [comment]
Agreeing with @ChristinaLK on usefulness of objectives-thinking, I copied in some of the content from the learning objectives episode and modified it to fit the focus on preparation (as opposed to design). I'm now happy with it but will leave it for a bit in others would like to comment on this rather substantial change.

**Comment by ErinBecker** [comment]
Thanks for the contribution @karenword, I really like how you've incorporated the additional practice in modifying formative assessments while still retaining some thinking about learning objectives and the learner profiles exercise. I'll leave this up until Tuesday and then merge if there are no objections.

**Pull request merged**
