### PR TITLE
Bloom's taxonomy infographic

### PR DESCRIPTION
**Pull request by raynamharris**
Addresses issue https://github.com/ErinBecker/instructor-training-reorg/issues/28

I'm open to using other infographics, but this one is CCBY

### CODE REVIEW

**Comment by ChristinaLK** [comment]
+1 from me.

**Comment by ErinBecker** [comment]
Thanks @raynamharris

**Comment by lexnederbragt** [comment]
@smcclatchy at the DIBSI TTT came with this one:

https://commons.wikimedia.org/wiki/File:Blooms_rose.svg

It addresses some of the points of this blog post http://teachlikeachampion.com/blog/blooms-taxonomy-pyramid-problem/ about the pyramid being a misleading model. And it is CC-BY...

**Comment by ChristinaLK** [comment]
@lexnederbragt can you open as new issue, if not done already?

**Pull request merged**
