### PR TITLE
removed instructor testimonials

### PR DESCRIPTION
**Pull request by raynamharris**
This addresses issue https://github.com/ErinBecker/instructor-training-reorg/issues/44

### CODE REVIEW

**Comment by weaverbel** [comment]
Good to go but there is a conflict that needs resolution first.

**Comment by ErinBecker** [comment]
@raynamharris I've tried to follow the command line instructions for resolving the conflicts, but I get an error telling me the patch is empty. I've tried a couple different ways to locate the patch file and not able to find it. So I haven't been able to figure out where the merge conflicts are (other than that they're in the 08 and 14 files). Do you have any idea what's going on here?

**Comment by weaverbel** [comment]
I think it's possible @raynamharris has deleted the fork @ErinBecker - I saw this kind of problem myself when I accidentally deleted a fork before a PR from it was merged.

**Comment by ChristinaLK** [comment]
Yup, I've re-created the PR in #152.

**Pull request closed without merging**
